macos_machine:
  - x86_64-apple-darwin13.4.0  # [not (osx and arm64)]
  - x86_64-apple-darwin13.4.0  # [not (osx and arm64)]
  - x86_64-apple-darwin13.4.0  # [not (osx and arm64)]
  - x86_64-apple-darwin13.4.0  # [not (osx and arm64)]
  - arm64-apple-darwin20.0.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64  # [not (osx and arm64)]
  - osx-64  # [not (osx and arm64)]
  - osx-64  # [not (osx and arm64)]
  - osx-64  # [not (osx and arm64)]
  - osx-arm64
  - osx-arm64
gfortran_version:
  - 7.5.0   # [not (osx and arm64)]
  - 9.4.0   # [not (osx and arm64)]
  - 10.3.0  # [not (osx and arm64)]
  - 11.2.0  # [not (osx and arm64)]
  - 10.3.0
  - 11.1.0
libgfortran_version:
  - 4.0.0   # [not (osx and arm64)]
  - 5.0.0   # [not (osx and arm64)]
  - 5.0.0   # [not (osx and arm64)]
  - 5.0.0   # [not (osx and arm64)]
  - 5.0.0
  - 5.0.0
zip_keys:
  - - gfortran_version
    - libgfortran_version
    - cross_target_platform
    - macos_machine
