macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64
  - osx-arm64
gfortran_version:
  - 7.5.0
  - 9.3.0
  - 10.3.0  # [osx and x86_64]
  - 10.2.1  # [osx and arm64]
  - 11.2.0  # [osx and x86_64]
  - 11.0.1  # [osx and arm64]
libgfortran_version:
  - 4.0.0
  - 5.0.0
  - 5.0.0  # [osx and x86_64]
  - 5.0.0  # [osx and arm64]
  - 5.0.0  # [osx and x86_64]
  - 5.0.0  # [osx and arm64]
zip_keys:
  - - cross_target_platform
    - macos_machine
  - - gfortran_version
    - libgfortran_version
